version: "3.8"

services:
  frontend:
    container_name: laravue_app_frontend
    build: .
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    volumes:
      - './app:/usr/laravue_app_frontend'